OL_OBJECTCLASS = dict([
(105,{'name': 'olAccount', 'descr': 'An Account object.'}),
(135,{'name': 'olAccountRuleCondition', 'descr': 'An AccountRuleCondition object.'}),
(106,{'name': 'olAccounts', 'descr': 'An Accounts object.'}),
(32,{'name': 'olAction', 'descr': 'An Action object.'}),
(33,{'name': 'olActions', 'descr': 'An Actions object.'}),
(21,{'name': 'olAddressEntries', 'descr': 'An AddressEntries object.'}),
(8,{'name': 'olAddressEntry', 'descr': 'An AddressEntry object.'}),
(7,{'name': 'olAddressList', 'descr': 'An AddressList object.'}),
(20,{'name': 'olAddressLists', 'descr': 'An AddressLists object.'}),
(170,{'name': 'olAddressRuleCondition', 'descr': 'An AddressRuleCondition object.'}),
(0,{'name': 'olApplication', 'descr': 'An Application object.'}),
(26,{'name': 'olAppointment', 'descr': 'An AppointmentItem object.'}),
(122,{'name': 'olAssignToCategoryRuleAction', 'descr': 'An AssignToCategoryRuleAction object.'}),
(5,{'name': 'olAttachment', 'descr': 'An Attachment object.'}),
(18,{'name': 'olAttachments', 'descr': 'An Attachments object.'}),
(169,{'name': 'olAttachmentSelection', 'descr': 'An AttachmentSelection object.'}),
(147,{'name': 'olAutoFormatRule', 'descr': 'An AutoFormatRule object.'}),
(148,{'name': 'olAutoFormatRules', 'descr': 'An AutoFormatRules object.'}),
(159,{'name': 'olCalendarModule', 'descr': 'A CalendarModule object.'}),
(151,{'name': 'olCalendarSharing', 'descr': 'A CalendarSharing object.'}),
(153,{'name': 'olCategories', 'descr': 'A Categories object.'}),
(152,{'name': 'olCategory', 'descr': 'A Category object.'}),
(130,{'name': 'olCategoryRuleCondition', 'descr': 'A CategoryRuleCondition object.'}),
(168,{'name': 'olClassBusinessCardView', 'descr': 'A BusinessCardView object.'}),
(139,{'name': 'olClassCalendarView', 'descr': 'A CalendarView object.'}),
(138,{'name': 'olClassCardView', 'descr': 'A CardView object.'}),
(137,{'name': 'olClassIconView', 'descr': 'An IconView object.'}),
(155,{'name': 'olClassNavigationPane', 'descr': 'A NavigationPane object.'}),
(183,{'name': 'olClassPeopleView', 'descr': 'A PeopleView object.'}),
(136,{'name': 'olClassTableView', 'descr': 'A TableView object.'}),
(140,{'name': 'olClassTimeLineView', 'descr': 'A TimelineView object.'}),
(174,{'name': 'olClassTimeZone', 'descr': 'A TimeZone object.'}),
(175,{'name': 'olClassTimeZones', 'descr': 'A TimeZones object.'}),
(154,{'name': 'olColumn', 'descr': 'A Column object.'}),
(149,{'name': 'olColumnFormat', 'descr': 'A ColumnFormat object.'}),
(150,{'name': 'olColumns', 'descr': 'A Columns object.'}),
(102,{'name': 'olConflict', 'descr': 'A Conflict object.'}),
(103,{'name': 'olConflicts', 'descr': 'A Conflicts object.'}),
(40,{'name': 'olContact', 'descr': 'A ContactItem object.'}),
(160,{'name': 'olContactsModule', 'descr': 'A ContactsModule object.'}),
(178,{'name': 'olConversation', 'descr': 'A Conversation object.'}),
(182,{'name': 'olConversationHeader', 'descr': 'A ConversationHeader object.'}),
(69,{'name': 'olDistributionList', 'descr': 'An ExchangeDistributionList object.'}),
(41,{'name': 'olDocument', 'descr': 'A DocumentItem object.'}),
(30,{'name': 'olException', 'descr': 'An Exception object.'}),
(29,{'name': 'olExceptions', 'descr': 'An Exceptions object.'}),
(111,{'name': 'olExchangeDistributionList', 'descr': 'An ExchangeDistributionList object.'}),
(110,{'name': 'olExchangeUser', 'descr': 'An ExchangeUser object.'}),
(34,{'name': 'olExplorer', 'descr': 'An Explorer object.'}),
(60,{'name': 'olExplorers', 'descr': 'An Explorers object.'}),
(2,{'name': 'olFolder', 'descr': 'A Folder object.'}),
(15,{'name': 'olFolders', 'descr': 'A Folders object.'}),
(172,{'name': 'olFolderUserProperties', 'descr': 'A UserDefinedProperties object.'}),
(171,{'name': 'olFolderUserProperty', 'descr': 'A UserDefinedProperty object.'}),
(37,{'name': 'olFormDescription', 'descr': 'A FormDescription object.'}),
(131,{'name': 'olFormNameRuleCondition', 'descr': 'A FormNameRuleCondition object.'}),
(129,{'name': 'olFormRegion', 'descr': 'A FormRegion object.'}),
(173,{'name': 'olFromRssFeedRuleCondition', 'descr': 'A FromRssFeedRuleCondition object.'}),
(132,{'name': 'olFromRuleCondition', 'descr': 'A ToOrFromRuleCondition object.'}),
(128,{'name': 'olImportanceRuleCondition', 'descr': 'An ImportanceRuleCondition object.'}),
(35,{'name': 'olInspector', 'descr': 'An Inspector object.'}),
(61,{'name': 'olInspectors', 'descr': 'An Inspectors object.'}),
(98,{'name': 'olItemProperties', 'descr': 'An ItemProperties object.'}),
(99,{'name': 'olItemProperty', 'descr': 'An ItemProperty object.'}),
(16,{'name': 'olItems', 'descr': 'An Items object.'}),
(42,{'name': 'olJournal', 'descr': 'A JournalItem object.'}),
(162,{'name': 'olJournalModule', 'descr': 'A JournalModule object.'}),
(43,{'name': 'olMail', 'descr': 'A MailItem object.'}),
(158,{'name': 'olMailModule', 'descr': 'A MailModule object.'}),
(124,{'name': 'olMarkAsTaskRuleAction', 'descr': 'A MarkAsTaskRuleAction object.'}),
(54,{'name': 'olMeetingCancellation', 'descr': 'A MeetingItem object that is a meeting cancellation notice.'}),
(181,{'name': 'olMeetingForwardNotification', 'descr': 'A MeetingItem object that is a notice about forwarding the meeting request.'}),
(53,{'name': 'olMeetingRequest', 'descr': 'A MeetingItem object that is a meeting request.'}),
(55,{'name': 'olMeetingResponseNegative', 'descr': 'A MeetingItem object that is a refusal of a meeting request.'}),
(56,{'name': 'olMeetingResponsePositive', 'descr': 'A MeetingItem object that is an acceptance of a meeting request.'}),
(57,{'name': 'olMeetingResponseTentative', 'descr': 'A MeetingItem object that is a tentative acceptance of a meeting request.'}),
(118,{'name': 'olMoveOrCopyRuleAction', 'descr': 'A MoveOrCopyRuleAction object.'}),
(1,{'name': 'olNamespace', 'descr': 'A NameSpace object.'}),
(167,{'name': 'olNavigationFolder', 'descr': 'A NavigationFolder object.'}),
(166,{'name': 'olNavigationFolders', 'descr': 'A NavigationFolders object.'}),
(165,{'name': 'olNavigationGroup', 'descr': 'A NavigationGroup object.'}),
(164,{'name': 'olNavigationGroups', 'descr': 'A NavigationGroups object.'}),
(157,{'name': 'olNavigationModule', 'descr': 'A NavigationModule object.'}),
(156,{'name': 'olNavigationModules', 'descr': 'A NavigationModules object.'}),
(125,{'name': 'olNewItemAlertRuleAction', 'descr': 'A NewItemAlertRuleAction object.'}),
(44,{'name': 'olNote', 'descr': 'A NoteItem object.'}),
(163,{'name': 'olNotesModule', 'descr': 'A NotesModule object.'}),
(144,{'name': 'olOrderField', 'descr': 'An OrderField object.'}),
(145,{'name': 'olOrderFields', 'descr': 'An OrderFields object.'}),
(66,{'name': 'olOutlookBarGroup', 'descr': 'An OutlookBarGroup object.'}),
(65,{'name': 'olOutlookBarGroups', 'descr': 'An OutlookBarGroups object.'}),
(63,{'name': 'olOutlookBarPane', 'descr': 'An OutlookBarPane object.'}),
(68,{'name': 'olOutlookBarShortcut', 'descr': 'An OutlookBarShortcut object.'}),
(67,{'name': 'olOutlookBarShortcuts', 'descr': 'An OutlookBarShortcuts object.'}),
(64,{'name': 'olOutlookBarStorage', 'descr': 'An OutlookBarStorage object.'}),
(180,{'name': 'olOutspace', 'descr': 'An AccountSelector object.'}),
(36,{'name': 'olPages', 'descr': 'A Pages object.'}),
(62,{'name': 'olPanes', 'descr': 'A Panes object.'}),
(123,{'name': 'olPlaySoundRuleAction', 'descr': 'A PlaySoundRuleAction object.'}),
(45,{'name': 'olPost', 'descr': 'A PostItem object.'}),
(112,{'name': 'olPropertyAccessor', 'descr': 'A PropertyAccessor object.'}),
(71,{'name': 'olPropertyPages', 'descr': 'A PropertyPages object.'}),
(70,{'name': 'olPropertyPageSite', 'descr': 'A PropertyPageSite object.'}),
(4,{'name': 'olRecipient', 'descr': 'A Recipient object.'}),
(17,{'name': 'olRecipients', 'descr': 'A Recipients object.'}),
(28,{'name': 'olRecurrencePattern', 'descr': 'A RecurrencePattern object.'}),
(101,{'name': 'olReminder', 'descr': 'A Reminder object.'}),
(100,{'name': 'olReminders', 'descr': 'A Reminders object.'}),
(47,{'name': 'olRemote', 'descr': 'A RemoteItem object.'}),
(46,{'name': 'olReport', 'descr': 'A ReportItem object.'}),
(78,{'name': 'olResults', 'descr': 'A Results object.'}),
(121,{'name': 'olRow', 'descr': 'A Row object.'}),
(115,{'name': 'olRule', 'descr': 'A Rule object.'}),
(117,{'name': 'olRuleAction', 'descr': 'A RuleAction object.'}),
(116,{'name': 'olRuleActions', 'descr': 'A RuleActions object.'}),
(127,{'name': 'olRuleCondition', 'descr': 'A RuleCondition object.'}),
(126,{'name': 'olRuleConditions', 'descr': 'A RuleConditions object.'}),
(114,{'name': 'olRules', 'descr': 'A Rules object.'}),
(77,{'name': 'olSearch', 'descr': 'A Search object.'}),
(74,{'name': 'olSelection', 'descr': 'A Selection object.'}),
(109,{'name': 'olSelectNamesDialog', 'descr': 'A SelectNamesDialog object.'}),
(133,{'name': 'olSenderInAddressListRuleCondition', 'descr': 'A SenderInAddressListRuleCondition object.'}),
(119,{'name': 'olSendRuleAction', 'descr': 'A SendRuleAction object.'}),
(104,{'name': 'olSharing', 'descr': 'A SharingItem object.'}),
(179,{'name': 'olSimpleItems', 'descr': 'A SimpleItems object.'}),
(177,{'name': 'olSolutionsModule', 'descr': 'A SolutionsModule object.'}),
(113,{'name': 'olStorageItem', 'descr': 'A StorageItem object.'}),
(107,{'name': 'olStore', 'descr': 'A Store object.'}),
(108,{'name': 'olStores', 'descr': 'A Stores object.'}),
(72,{'name': 'olSyncObject', 'descr': 'A SyncObject object.'}),
(73,{'name': 'olSyncObjects', 'descr': 'A SyncObjects object.'}),
(120,{'name': 'olTable', 'descr': 'A Table object.'}),
(48,{'name': 'olTask', 'descr': 'A TaskItem object.'}),
(49,{'name': 'olTaskRequest', 'descr': 'A TaskRequestItem object.'}),
(51,{'name': 'olTaskRequestAccept', 'descr': 'A TaskRequestAcceptItem object.'}),
(52,{'name': 'olTaskRequestDecline', 'descr': 'A TaskRequestDeclineItem object.'}),
(50,{'name': 'olTaskRequestUpdate', 'descr': 'A TaskRequestUpdateItem object.'}),
(161,{'name': 'olTasksModule', 'descr': 'A TasksModule object.'}),
(134,{'name': 'olTextRuleCondition', 'descr': 'A TextRuleCondition object.'}),
(172,{'name': 'olUserDefinedProperties', 'descr': 'A UserDefinedProperties object.'}),
(171,{'name': 'olUserDefinedProperty', 'descr': 'A UserDefinedProperty object.'}),
(38,{'name': 'olUserProperties', 'descr': 'A UserProperties object.'}),
(39,{'name': 'olUserProperty', 'descr': 'A UserProperty object.'}),
(80,{'name': 'olView', 'descr': 'A View object.'}),
(142,{'name': 'olViewField', 'descr': 'A ViewField object.'}),
(141,{'name': 'olViewFields', 'descr': 'A ViewFields object.'}),
(146,{'name': 'olViewFont', 'descr': 'A ViewFont object.'}),
(79,{'name': 'olViews', 'descr': 'A Views object.'}),    
])

OL_MAILRECIPIENTTYPE = dict([
(3,{'name': 'olBCC', 'descr': 'The recipient is specified in the BCC property of the Item.'}),
(2,{'name': 'olCC', 'descr': 'The recipient is specified in the CC property of the Item.'}),
(0,{'name': 'olOriginator', 'descr': 'Originator (sender) of the Item.'}),
(1,{'name': 'olTo', 'descr': 'The recipient is specified in the To property of the Item.'}),
])

'''
OL_ = dict([])
'''