VIS_PAPERSIZES = dict([(8,{'name': 'visPaperSizeA3', 'descr':'A3 297 x 420 mm'}),
(9,{'name': 'visPaperSizeA4', 'descr':'A4 210 x 297 mm'}),
(11,{'name': 'visPaperSizeA5', 'descr':'A5 148 x 210 mm'}),
(12,{'name': 'visPaperSizeB4', 'descr':'B4 (JIS) 250 x 354 mm'}),
(13,{'name': 'visPaperSizeB5', 'descr':'B5 (JIS) 182 x 257 mm'}),
(14,{'name': 'visPaperSizeFolio', 'descr':'Folio 8 1/2 x 13 in.'}),
(5,{'name': 'visPaperSizeLegal', 'descr':'Legal 8 1/2 x 14 in.'}),
(1,{'name': 'visPaperSizeLetter', 'descr':'Letter 8 1/2 x 11 in.'}),
(18,{'name': 'visPaperSizeNote', 'descr':'Note 8 1/2 x 11 in.'}),
(24,{'name': 'visPaperSizeSizeC', 'descr':'C size sheet 17 x 22 in.'}),
(25,{'name': 'visPaperSizeSizeD', 'descr':'D size sheet 22 x 34 in.'}),
(26,{'name': 'visPaperSizeSizeE', 'descr':'E size sheet 34 x 44 in.'}),
(0,{'name': 'visPaperSizeUnknown', 'descr':'Unknown'}),])

VIS_OBJECTTYPES = dict([(31,{'name': 'visObjTypeAddon', 'descr':'Addon object'}),
(32,{'name': 'visObjTypeAddons', 'descr':'Addons collection'}),
(51,{'name': 'visObjTypeApplicationSettings', 'descr':'ApplicationSettings object'}),
(3,{'name': 'visObjTypeApp', 'descr':'Application object'}),
(4,{'name': 'visObjTypeCell', 'descr':'Cell object'}),
(5,{'name': 'visObjTypeChars', 'descr':'Characters object'}),
(29,{'name': 'visObjTypeColor', 'descr':'Color object'}),
(30,{'name': 'visObjTypeColors', 'descr':'Colors collection'}),
(74,{'name': 'visObjTypeComment', 'descr':'Comment object'}),
(74,{'name': 'visObjTypeComments', 'descr':'Comments collection'}),
(8,{'name': 'visObjTypeConnect', 'descr':'Connect object'}),
(9,{'name': 'visObjTypeConnects', 'descr':'Connects collection'}),
(60,{'name': 'visObjTypeContainerProperties', 'descr':'ContainerProperties collection'}),
(42,{'name': 'visObjTypeCurve', 'descr':'Curve object'}),
(56,{'name': 'visObjTypeDataColumn', 'descr':'DataColumn object'}),
(55,{'name': 'visObjTypeDataColumns', 'descr':'DataColumns collection'}),
(54,{'name': 'visObjTypeDataConnection', 'descr':'DataConnection object'}),
(53,{'name': 'visObjTypeDataRecordset', 'descr':'DataRecordset object'}),
(57,{'name': 'visObjTypeDataRecordsetChangedEvent', 'descr':'DataRecordsetChangedEvent object'}),
(52,{'name': 'visObjTypeDataRecordsets', 'descr':'DataRecordsets collection'}),
(10,{'name': 'visObjTypeDoc', 'descr':'Document object'}),
(11,{'name': 'visObjTypeDocs', 'descr':'Documents collection'}),
(34,{'name': 'visObjTypeEventList', 'descr':'EventList collection'}),
(33,{'name': 'visObjTypeEvent', 'descr':'Event object'}),
(27,{'name': 'visObjTypeFont', 'descr':'Font object'}),
(28,{'name': 'visObjTypeFonts', 'descr':'Fonts collection'}),
(36,{'name': 'visObjTypeGlobal', 'descr':'Global object'}),
(59,{'name': 'visObjTypeGraphicItem', 'descr':'GraphicItem object'}),
(58,{'name': 'visObjTypeGraphicItems', 'descr':'GraphicItems collection'}),
(37,{'name': 'visObjTypeHyperlink', 'descr':'Hyperlink object'}),
(43,{'name': 'visObjTypeHyperlinks', 'descr':'Hyperlinks collection'}),
(50,{'name': 'visObjTypeKeyboardEvent', 'descr':'KeyboardEvent object'}),
(25,{'name': 'visObjTypeLayer', 'descr':'Layer object'}),
(26,{'name': 'visObjTypeLayers', 'descr':'Layers collection'}),
(47,{'name': 'visObjTypeMasterShortcut', 'descr':'MasterShortcut object'}),
(46,{'name': 'visObjTypeMasterShortcuts', 'descr':'MasterShortcuts collection'}),
(12,{'name': 'visObjTypeMaster', 'descr':'Master object'}),
(13,{'name': 'visObjTypeMasters', 'descr':'Masters collection'}),
(49,{'name': 'visObjTypeMouseEvent', 'descr':'MouseEvent object'}),
(62,{'name': 'visObjTypeMovedSelectionEvent', 'descr':'MovedSelectionEvent object'}),
(48,{'name': 'visObjTypeMSGWrap', 'descr':'MSGWrap object'}),
(39,{'name': 'visObjTypeOLEObject', 'descr':'OLEObject object'}),
(38,{'name': 'visObjTypeOLEObjects', 'descr':'OLEObjects collection'}),
(14,{'name': 'visObjTypePage', 'descr':'Page object'}),
(15,{'name': 'visObjTypePages', 'descr':'Pages collection'}),
(41,{'name': 'visObjTypePath', 'descr':'Path object'}),
(40,{'name': 'visObjTypePaths', 'descr':'Paths collection'}),
(61,{'name': 'visObjTypeRelatedShapePairEvent', 'descr':'RelatedShapePairEvent object'}),
(71,{'name': 'visObjTypeReplaceShapesEvent', 'descr':'ReplaceShapesEvent object'}),
(45,{'name': 'visObjTypeRow', 'descr':'Row object'}),
(44,{'name': 'visObjTypeSection', 'descr':'Section object'}),
(16,{'name': 'visObjTypeSelection', 'descr':'Selection object'}),
(63,{'name': 'visObjTypeServerPublishOptions', 'descr':'ServerPublishOptions object'}),
(17,{'name': 'visObjTypeShape', 'descr':'Shape object'}),
(18,{'name': 'visObjTypeShapes', 'descr':'Shapes collection'}),
(19,{'name': 'visObjTypeStyle', 'descr':'Style object'}),
(20,{'name': 'visObjTypeStyles', 'descr':'Styles object'}),
(1,{'name': 'visObjTypeUnknown', 'descr':'Unknown object'}),
(64,{'name': 'visObjTypeValidation', 'descr':'Validation object'}),
(70,{'name': 'visObjTypeValidationIssue', 'descr':'ValidationIssue object'}),
(69,{'name': 'visObjTypeValidationIssues', 'descr':'ValidationIssues collection'}),
(68,{'name': 'visObjTypeValidationRule', 'descr':'ValidationRule object'}),
(67,{'name': 'visObjTypeValidationRules', 'descr':'ValidationRules collection'}),
(66,{'name': 'visObjTypeValidationRuleSet', 'descr':'ValidationRuleSet object'}),
(65,{'name': 'visObjTypeValidationRuleSets', 'descr':'ValidationRuleSets collection'}),
(21,{'name': 'visObjTypeWindow', 'descr':'Window object'}),
(22,{'name': 'visObjTypeWindows', 'descr':'Windows collection'})])

VIS_PAGETYPES = dict([(0,{'name': 'visPageTypeInval', 'descr':'Not a Microsoft Visio page.'}),
(2,{'name': 'visTypeBackground', 'descr':'A background page.'}),
(1,{'name': 'visTypeForeground', 'descr':'A foreground page.'}),
(3,{'name': 'visTypeMarkup', 'descr':'An annotation page.'})])

VIS_SHAPETYPES = dict([(32,{'name': 'visTypeBitmap', 'descr':'Returned by Shape.ForeignType if the shape is a bitmap.'}),
(6,{'name': 'visTypeDoc', 'descr':'The document\'s DocumentSheet.'}),
(4,{'name': 'visTypeForeignObject', 'descr':'An imported shape.'}),
(2,{'name': 'visTypeGroup', 'descr':'A shape that contains other shapes.'}),
(5,{'name': 'visTypeGuide', 'descr':'A shape that is a guide.'}),
(64,{'name': 'visTypeInk', 'descr':'Returned by Shape.ForeignType if the shape is ink.'}),
(0,{'name': 'visTypeInval', 'descr':'The type of no shape. Means all types when used as filter code.'}),
(1024,{'name': 'visTypeIsControl', 'descr':'Returned by Shape.ForeignType if the shape is a control.'}),
(512,{'name': 'visTypeIsEmbedded', 'descr':'Returned by Shape.ForeignType if the shape is embedded.'}),
(256,{'name': 'visTypeIsLinked', 'descr':'Returned by Shape.ForeignType if the shape is linked.'}),
(32768,{'name': 'visTypeIsOLE2', 'descr':'Returned by Shape.ForeignType if the shape is linked, embedded, or a control.'}),
(16,{'name': 'visTypeMetafile', 'descr':'Returned by Shape.ForeignType if the shape is a metafile.'}),
(1,{'name': 'visTypePage', 'descr':'Page\'s or master\'s PageSheet property.'}),
(3,{'name': 'visTypeShape', 'descr':'Native Microsoft Visio shape.'})])

